### ISSUE TITLE
[Github Classroom] Restricted Access to Repo

### ISSUE THREAD

**Issue by I0x0I** [tamu-edu-students/24F-CSCE313-FAQ#2]
Leave a common below so we can manually assign your repo access.

See also [[1]](https://github.com/orgs/community/discussions/130738#discussioncomment-10674172) and [[2]]( https://github.com/orgs/community/discussions/137628#discussioncomment-10673927)

**Comment by extragi** [comment]
I am having issues with the repository!

**Comment by jColbor** [comment]
I need access

**Comment by Math-Maniac7** [comment]
I am unable to access lab2. Thank you guys for doing this!

**Comment by I0x0I** [comment]
Existing access issues should have been resolved by the script from [[2]](https://github.com/orgs/community/discussions/137628#discussioncomment-10677279).

[fix-access.txt](https://github.com/user-attachments/files/17046477/fix-access.txt)

**Comment by Shreyan9** [comment]
Need Access

**Comment by I0x0I** [comment]
@Shreyan9 You should have access since earlier this morning, could you confirm the issue still exist?

**Comment by Shreyan9** [comment]
> @Shreyan9 You should have access since earlier this morning, could you confirm the issue still exist?

Cloning into 'lab-exercise-2-Shreyan9.'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists 


Still getting this, checked my ssh key was added to github as well.

**Comment by I0x0I** [comment]
@Shreyan9 That might be a different problem, could you confirm that when you open the Github classroom assignment link you are directed to a restricted access page as shown in the enclosed picture?

![image](https://github.com/user-attachments/assets/2014b94f-0103-4237-b5c4-51a658d36afc)

If you can see the regular assignment accepted page you might want to check if you can clone other repos, which will verify your VM ssh keys.
